# Generated by Django 5.0.7 on 2024-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="category",
            field=models.CharField(default="equipment", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="Training/profile_pics"
            ),
        ),
    ]
